# Английская раскладка (стандарт)
map ctrl+c copy_to_clipboard
map ctrl+v paste_from_clipboard
map ctrl+z send_text all \x1a
map ctrl+shift+z send_text all \x19

# Русская раскладка (прямое сопоставление символов)
map ctrl+с copy_to_clipboard
map ctrl+м paste_from_clipboard
map ctrl+я send_text all \x1a
map ctrl+shift+я send_text all \x19

# Сигнал прерывания процесса в терминале
map ctrl+shift+c send_text all \x03
confirm_os_window_close 0


# Настройки прозрачности
background_opacity 0.75
dynamic_background_opacity yes